- name: load mapping of HCTLs to devices
  shell: lsblk -o NAME,HCTL --json
  check_mode: no
  changed_when: False
  register: lsblk_output

- name: create mapping of hctl to device
  set_fact:
    disk_hctl_to_device: "{{ disk_hctl_to_device|default({}) | combine({item.hctl: item.name}) }}"
  with_items: "{{ (lsblk_output.stdout | from_json).blockdevices }}"

- name: create filesystems
  filesystem:
    device: /dev/{{ disk_hctl_to_device[item.hctl] }}
    fstype: "{{ item.fstype }}"
  with_items:
    - "{{ extra_disks }}"

- name: create mountpoints
  file:
    path: "{{ item.mount }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ extra_disks }}"

- name: mount disks
  mount:
    src: /dev/{{ disk_hctl_to_device[item.hctl] }}
    fstype: "{{ item.fstype }}"
    path: "{{ item.mount }}"
    state: mounted
  with_items:
    - "{{ extra_disks }}"
