---

- name: Rob Lazzurs
  user:
    name=lazzurs
    shell=/bin/bash

- name: Rob Lazzurs key
  authorized_key:
      user: lazzurs
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/lazzurs.pub"

- name: Sean Privett
  user:
    name=sean
    shell=/bin/bash

- name: Sean Privett key
  authorized_key:
      user: sean
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/sean.pub"

- name: James Glossop
  user:
    name=jamesglossop
    shell=/bin/bash

- name: James Glossop key
  authorized_key:
      user: jamesglossop
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/jamesglossop.pub"
