---

- name: passwordless sudo for admin
  copy:
    dest: /etc/sudoers.d/admin
    content: |
      %admin ALL=(ALL) NOPASSWD: ALL
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'

- name: John Hackett
  user:
    name: johnhackett
    shell: /bin/bash
    groups: admin

- name: John Hackett key
  authorized_key:
      user: johnhackett
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/johnhackett.pub"


- name: Glen Mailer
  user:
    name: glenmailer
    shell: /bin/bash
    groups: admin

- name: Glen Mailer key
  authorized_key:
      user: glenmailer
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/glenmailer.pub"

- name: Sean Privett
  user:
    name: sean
    shell: /bin/bash

- name: Sean Privett key
  authorized_key:
      user: sean
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/sean.pub"

- name: Andrew Walker
  user:
    name: awalker
    shell: /bin/bash

- name: Andrew Walker key
  authorized_key:
      user: awalker
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/awalker.pub"

- name: James Glossop
  user:
    name: jamesglossop
    shell: /bin/bash

- name: James Glossop key
  authorized_key:
      user: jamesglossop
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/jamesglossop.pub"

- name: Steve Wilson
  user:
    name: stevenwilson
    shell: /bin/bash

- name: Steve Wilson key
  authorized_key:
      user: stevenwilson
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/stevenwilson.pub"
