---

- name: passwordless sudo for admin
  copy:
    dest: /etc/sudoers.d/admin
    content: |
      %admin ALL=(ALL) NOPASSWD: ALL
    owner: root
    group: root
    mode: 0644
    validate: 'visudo -cf %s'

- name: Rob Lazzurs
  user:
    name: lazzurs
    shell: /bin/bash
    groups: admin

- name: Rob Lazzurs key
  authorized_key:
      user: lazzurs
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/lazzurs.pub"

- name: Glen Mailer
  user:
    name: glenmailer
    shell: /bin/bash
    groups: admin

- name: Glen Mailer key
  authorized_key:
      user: glenmailer
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/glenmailer.pub"

- name: Sean Privett
  user:
    name: sean
    shell: /bin/bash

- name: Sean Privett key
  authorized_key:
      user: sean
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/sean.pub"

- name: James Glossop
  user:
    name: jamesglossop
    shell: /bin/bash

- name: James Glossop key
  authorized_key:
      user: jamesglossop
      key: "{{ item }}"
      state: present
  with_file:
      - "files/keys/{{ env }}/jamesglossop.pub"
