version: "3"

services:
        hub-db:
                image: mojdigitalstudio/digital-hub-db
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: hubdb
                        MYSQL_USER: hubdb_user
                        MYSQL_PASSWORD: hubdb_pass
                ports:
                        - 3306:3306
                            

        hub-memcache:
                image: memcached

        hub-fe:
                image: mojdigitalstudio/digital-hub-fe
                depends_on: 
                        - hub-be
                environment:
                        API_URI: http://hub-be/
                ports:
                        - 80:80
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost"]
                        interval: 1m
                        timeout: 30s
                        retries: 3

        hub-be:
                image: mojdigitalstudio/digital-hub-be
                depends_on: 
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                        HUB_EXT_FILE_URL: /sites/default/files
                        PHP_MEMORY_LIMIT: 256M
                        PHP_UPLOAD_MAX_FILE_SIZE: 256M
                        PHP_POST_MAX_SIZE: 256M
                ports:
                        - 8182:80
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost"]
                        interval: 1m
                        timeout: 30s
                        retries: 3
