version: "3"

services:
        hub-db:
                image: mariadb
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: hubdb
                        MYSQL_USER: hubdb_user
                        MYSQL_PASSWORD: hubdb_pass
                volumes:
                        - ./db_dump:/docker-entrypoint-initdb.d
                ports:
                        - 3306:3306

        hub-memcache:
                image: memcached

        hub-fe:
                image: mojdigitalstudio/digital-hub-fe
                depends_on: 
                        - hub-be
                        - hub-memcache
                environment:
                        API_URI: http://hub-be/
                ports:
                        - 8181:80
                volumes:
                        - ./moj-fe/:/var/www/hub/

        hub-be:
                image: mojdigitalstudio/digital-hub-be
                depends_on: 
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                        HUB_EXT_FILE_URL: http://localhost:8181/sites/default/files
                        PHP_MEMORY_LIMIT: 500M
                        PHP_UPLOAD_MAX_FILE_SIZE: 500M
                        PHP_POST_MAX_SIZE: 500M
                volumes:
                        - ./moj-be/:/var/www/html/
                ports:
                        - 8182:80

        hub-drush:
                image: drupaldocker/drush
                depends_on:
                        - hub-be
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                volumes:
                        - ./moj-be/:/var/www/html/
                entrypoint:
                        - drush
                        - '--root=/var/www/html/'

        hub-drupal:
                image: drupaldocker/console
                depends_on:
                        - hub-be
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                volumes:
                        - ./moj-be/:/var/www/html/
                entrypoint:
                        - drupal
                        - '--root=/var/www/html/'
