version: "3"

services:
  hub-db:
    container_name: hub-db
    image: mariadb

  hub-memcache:
    image: memcached

  hub-node:
    container_name: hub-node
    image: mojdigitalstudio/digital-hub-node
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - hub-be
    environment:
      HUB_API_ENDPOINT: http://hub-be
      APP_TIMEOUT: 60.0
      PORT: 3000
      APP_NAME: HMP Dev
      ELASTICSEARCH_ENDPOINT: http://hub-elasticsearch:9200
      BACKEND_URL: http://hub-be
    ports:
      - 10001:3000

  hub-be:
    container_name: hub-be
    image: mojdigitalstudio/digital-hub-be
    depends_on:
      - hub-db
      - hub-elasticsearch
    ports:
      - 11001:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 30s
      retries: 1

  hub-elasticsearch:
    container_name: hub-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ulimits:
     memlock:
       soft: -1
       hard: -1
