version: "3"

services:
        hub-db:
                image: mojdigitalstudio/digital-hub-db
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: hubdb
                        MYSQL_USER: hubdb_user
                        MYSQL_PASSWORD: hubdb_pass
                ports:
                        - 3306:3306

        hub-memcache:
                image: memcached

        hub-node:
                image: mojdigitalstudio/digital-hub-node
                user: "node"
                working_dir: /home/node/app
                depends_on:
                        - hub-be
                environment:
                        HUB_API_ENDPOINT: http://hub-be/v1/api
                        APP_TIMEOUT: 60.0
                        PORT: 3000
                ports:
                        - 8183:3000
                volumes:
                        - ./moj-node/server:/home/node/app/server
                        - ./moj-node/test:/home/node/app/test
                        - ./moj-node/assets:/home/node/app/assets

        hub-fe:
                image: mojdigitalstudio/digital-hub-fe
                depends_on:
                        - hub-be
                        - hub-memcache
                environment:
                        API_URI: http://hub-be/
                        APP_TIMEOUT: 60.0
                ports:
                        - 8181:80
                volumes:
                        - ./moj-fe/:/var/www/hub/
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost"]
                        interval: 15s
                        timeout: 30s
                        retries: 1

        hub-be:
                image: mojdigitalstudio/digital-hub-be
                depends_on:
                        2- hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                        HUB_EXT_FILE_URL: http://localhost:8181/sites/default/files
                        PHP_MEMORY_LIMIT: 500M
                        PHP_UPLOAD_MAX_FILE_SIZE: 500M
                        PHP_POST_MAX_SIZE: 500M
                        SIMPLETEST_DB: mysql://hubdb_user:hubdb_pass@localhost/hubdb
                        XDEBUG_IP: 127.0.0.1 # Replace with your machines IP: $ ipconfig getifaddr en0 
                volumes:
                        - ./moj-be/:/var/www/html/
                ports:
                        - 8182:80
                healthcheck:
                        test: ["CMD", "curl", "-f", "http://localhost"]
                        interval: 15s
                        timeout: 30s
                        retries: 1

        hub-drush:
                image: drupaldocker/drush
                depends_on:
                        - hub-be
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                volumes:
                        - ./moj-be/:/var/www/html/
                entrypoint:
                        - drush
                        - '--root=/var/www/html/'

        hub-drupal:
                image: drupaldocker/console
                depends_on:
                        - hub-be
                        - hub-db
                environment:
                        HUB_DB_ENV_MYSQL_DATABASE: hubdb
                        HUB_DB_ENV_MYSQL_USER: hubdb_user
                        HUB_DB_ENV_MYSQL_PASSWORD: hubdb_pass
                        HUB_DB_PORT_3306_TCP_ADDR: hub-db
                volumes:
                        - ./moj-be/:/var/www/html/
                entrypoint:
                        - drupal
                        - '--root=/var/www/html/'
        hub-api-docs:
                image: mojdigitalstudio/digital-hub-api-docs
                depends_on:
                        - hub-db
                        - hub-be
                environment:
                        API_URL: ./config/swagger.json
                volumes:
                        - ./moj-api-docs/config:/var/www/html/config
                ports:
                        - 8184:8080
        hub-matomo:
                image: matomo:3-apache
                depends_on:
                        - hub-matomo-db
                ports:
                        - 12002
        hub-matomo-db:
                image: mojdigitalstudio/digital-hub-matomo-db
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_DATABASE: matomo_db
                        MYSQL_USER: matomo_user
                        MYSQL_PASSWORD: matomo_pass
                volumes:
                        - /data/digital-hub-matmomo-db/var/lib/mysql/data:/var/lib/mysql/data
