version: "3"

services:
  hub-db:
    env_file:
      - hub-db.env
    volumes:
      - mariadb_data:/var/lib/mysql

  hub-node:
    build:
      context: ./moj-node
    environment:
      MOCK_AUTH: 'true'

    volumes:
      - ./moj-node/server:/home/node/app/server
      - ./moj-node/test:/home/node/app/test
      - ./moj-node/assets:/home/node/app/assets

  hub-be:
    build:
      context: ./moj-be
    env_file:
      - hub-be.env
    volumes:
      - ./moj-be/modules/custom:/var/www/html/modules/custom
      - ./moj-be/profiles:/var/www/html/profiles
      - ./moj-be/themes:/var/www/html/themes
      - ./moj-be/sites:/var/www/html/sites

  hub-elasticsearch:
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

volumes:
  mariadb_data:
