version: "3"

services:
    hub-node:
        volumes:
            - ./moj-node/server:/home/node/app/server
            - ./moj-node/test:/home/node/app/test
            - ./moj-node/assets:/home/node/app/assets

    hub-fe:
        volumes:
            - ./moj-fe/:/app

    hub-be:
        volumes:
            - ./moj-be/:/var/www/html/

    hub-matomo:
        volumes:
            - ./moj-reporting/config:/var/www/html/config:rw
            - ./moj-reporting/digital-hub-matmomo-db/var/lib/mysql/data:/var/lib/mysql/data
            - ./logs:/var/www/html/logs