version: "3"

services:
  drupal-db:
    image: mariadb
    env_file:
      - drupal-db.env
    volumes:
      - drupal_db_data:/var/lib/mysql
      - ./drupal-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  drupal:
    # TODO: rename digital-hub-be to prisoner-content-hub-drupal
    image: mojdigitalstudio/digital-hub-be
    depends_on:
      - drupal-db
      - hub-elasticsearch
    env_file:
      - drupal.env
    ports:
      - 11001:8080

  hub-frontend:
    # TODO: rename digital-hub-be to prisoner-content-hub-frontend
    image: mojdigitalstudio/digital-hub-node
    depends_on:
      - drupal
      - hub-elasticsearch
    env_file:
      - hub-frontend.env
    ports:
      - 10001:3000

  # This container nameis referenced from Drupal DB config, so it should
  # match production
  # TODO: add init script to set Drupal ES connector from environment variable
  hub-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false

    # TODO: do we need these for local dev?
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  drupal_db_data:
  elasticsearch_data:
