apiVersion: v1
kind: Service
metadata:
  name: {{ include "prisoner-content-hub.fullname" . }}-{{ .Values.nprrelay.name }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.nprrelay.servicePort }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "prisoner-content-hub.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisoner-content-hub.fullname" . }}-{{ .Values.nprrelay.name }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nprrelay.replicaCount }}
  selector:
    matchLabels:
      {{- include "prisoner-content-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisoner-content-hub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.nprrelay.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.application.liveness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.liveness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.application.readiness.endpoint }}
              port: http
            initialDelaySeconds: {{ .Values.application.readiness.delaySeconds }}
            timeoutSeconds: {{ .Values.application.readiness.timeoutSeconds }}
          volumeMounts:
            - name: icecast-config
              mountPath: "/etc/icecast"
              readOnly: true
      volumes:
      - name: icecast-config
        secret:
          secretName: {{ .Values.nprrelay.secretName }}
