apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.nprrelay.secretName }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
data:
  icecast.xml: {{ include "prisoner-content-hub.icecastConfig" . | b64enc }}
