apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.slack.secretName }}
  labels:
    {{- include "prisoner-content-hub.labels" . | nindent 4 }}
data:
  webhook_url: {{ .Values.slack.webhookUrl | b64enc }}
