version: 2

jobs:
    build:
        working_directory: ~/digital-hub
        docker:
            - image: mojdigitalstudio/digital-hub-fe
            - image: mojdigitalstudio/digital-hub-be
            - image: mojdigitalstudio/digital-hub-db
        steps:
            - checkout
            - run:
                name: Run frontend tests
                command: cd moj-fe && make test
            - run:
                name: Run Drupal backend tests
                command: cd moj-be && make test
            - run:
                name: Build frontend container
                command: cd moj-fe && make build && make push
            - run:
                name: Build backend container
                command: cd moj-be && make build && make push

