version: 2

jobs:
    build:
        working_directory: ~/digital-hub
        docker:
            - image: mojdigitalstudio/circleci-build-container
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build frontend container
                command: cd moj-fe && make build && make push
            - run:
                name: Build backend container
                command: cd moj-be && make build && make push
            - run:
                name: Run frontend tests
                command: cd moj-fe && make test
            - run:
                name: Run Drupal backend tests
                command: cd moj-be && make test
            - run:
                name: Build DB container
                command: cd db && make build && make push
            - deploy:
                name: Deploy to development environment
                command: |
                    ssh -o StrictHostKeyChecking=no -p 50000 -l docker -fNL /home/circleci/docker.sock:/var/run/docker.sock ssh.dev.hub.service.hmpps.dsd.io
                    DOCKER_TLS_VERIFY= DOCKER_HOST=unix:///home/circleci/docker.sock docker --tls=false stack up -c docker-compose-prod.yml hub-dev
            - run:
                name: Test development frontend
                command: |
                    cd capybara
                    bundle install
                    bundle exec rake test
