version: 2

jobs:
    build:
        working_directory: ~/digital-hub
        docker:
            - image: mojdigitalstudio/circleci-build-container
        steps:
            - checkout
            - setup_remote_docker:
                reusable: true
            - restore_cache:
                key: moj-fe/node_modules-{{ checksum "moj-fe/package.json" }}
                key: moj-fe/node_modules
            - restore_cache:
                key: moj-fe/vendor-{{ checksum "moj-fe/composer.json" }}
                key: moj-fe/vendor
            - run:
                name: Build frontend container
                command: cd moj-fe && make build
            - save_cache:
                key: moj-fe/node_modules-{{ checksum "moj-fe/package.json" }}
                paths:
                    - ./moj-fe/node_modules
            - save_cache:
                key: moj-fe/vendor-{{ checksum "moj-fe/composer.json" }}
                paths:
                    - ./moj-fe/vendor
            - restore_cache:
                key: moj-node/node_modules-{{ checksum "moj-node/package.json" }}
                key: moj-node/node_modules
            - run:
                name: Build node frontend container
                command: cd moj-node && make build
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules

            - restore_cache:
                key: moj-be/vendor-{{ checksum "moj-be/composer.json" }}
                key: moj-be/vendor
            - run:
                name: Build backend container
                command: cd moj-be && make build
            #- run:
                #name: Build API docs
                #command: cd moj-be && make build-api-docs
            - save_cache:
                key: moj-be/vendor-{{ checksum "moj-be/composer.json" }}
                paths:
                    - ./moj-be/vendor
            #- run:
                #name: Run frontend tests
                #command: cd moj-fe && make test
            # - run:
                # name: Run Drupal backend tests
                # command: cd moj-be && make test
            - run:
                name: Build DB container
                command: cd db && make build
            - run:
                name: push fe to docker
                command: cd moj-fe && make push
            - run:
                name: push be to docker
                command: cd moj-be && make push
            - run:
                name: push node fe to docker
                command: cd moj-node && make push
            - run:
                name: push db to docker
                command: cd db && make push
