version: 2

jobs:
    build:
        working_directory: ~/digital-hub
        docker:
            - image: notnoopci/php:7-zts-node-browsers
        steps:
            - run:
                name: Install Docker into the container
                command: curl https://get.docker.com/ | sudo bash
            - run:
                name: Allow circleci user to run docker
                command: sudo usermod -aG docker circleci
            - checkout
            - run:
                name: Build frontend container
                command: cd moj-fe && make build && make push
            - run:
                name: Build backend container
                command: cd moj-be && make build && make push
            - run:
                name: Run frontend tests
                command: cd moj-fe && make test
            - run:
                name: Run Drupal backend tests
                command: cd moj-be && make test

