sudo_groups:
  - admin
  - studio

# This user with uid 80 specifically is used to ensure the
# backend container can read/write from the host mounted volume
system_users:
  - name: hub
    uid: 80
    comment: Hub Content Share

# We use hctl here as this is stable
# the final number matches the LUN field from the azure portal
extra_disks:
  - hctl: "3:0:0:0"
    label: data
    fstype: xfs
    mount: /data
    owner: hub
  - hctl: "3:0:0:1"
    label: content
    fstype: xfs
    mount: /content
    owner: hub

hub_containers:
  - image: memcached
    name: hub-memcache
  - image: mojdigitalstudio/digital-hub-db
    name: hub-db
  - image: mojdigitalstudio/digital-hub-be
    name: hub-be
  - image: mojdigitalstudio/digital-hub-fe
    name: hub-fe

nginx_upstreams:
  - name: hub_fe
    servers:
      - "localhost:10001"
  - name: hub_be
    servers:
      - "localhost:11001"

nginx_vhosts:
  - listen: 80
    server_name: "{{ hub_frontend_host }}"
    state: present
    extra_parameters: |
      ignore_invalid_headers off;
      location / {
        proxy_pass http://hub_fe;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }
  - listen: 80
    server_name: "{{ hub_backend_host }}"
    state: present
    extra_parameters: |
      ignore_invalid_headers off;
      location / {
        proxy_pass http://hub_be;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }

firewall_state: started
firewall_enabled_at_boot: true
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
