sudo_groups:
  - admin
  - studio

# This user with uid 80 specifically is used to ensure the
# backend container can read/write from the host mounted volume
system_users:
  - name: hub
    uid: 80
    comment: Hub Content Share

# We use hctl here as this is stable
# the final number matches the LUN field from the azure portal
extra_disks:
  - hctl: "3:0:0:0"
    label: data
    fstype: xfs
    mount: /data
    owner: hub
  - hctl: "3:0:0:1"
    label: content
    fstype: xfs
    mount: /content
    owner: hub

hub_containers:
  - image: memcached
    name: hub-memcache
  - image: mojdigitalstudio/digital-hub-db
    name: hub-db
  - image: mojdigitalstudio/digital-hub-be
    name: hub-be
  - image: mojdigitalstudio/digital-hub-fe
    name: hub-fe
  - image: mojdigitalstudio/digital-hub-node
    name: hub-node
  - image: matomo:3-apache
    name: hub-matomo
  - image: mojdigitalstudio/digital-hub-db
    name: hub-matomo-db

hub_sites:
  - upstream_name: hub_node
    upstream_port: 10001
    domain: "{{ hub_frontend_host }}"
  - upstream_name: hub_fe
    upstream_port: 10002
    domain: "{{ hub_frontend_host }}"
  - upstream_name: hub_be
    upstream_port: 11001
    domain: "{{ hub_backend_host }}"

firewall_state: started
firewall_enabled_at_boot: true
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
