nameOverride: ""
fullnameOverride: ""

tier: frontend

npr:
  name: npr-live
  path: npr-live
  servicePort: 80
  remotePort: 8000

service:
  type: ClusterIP
  clusterIP: None

ingress:
  enabled: true  
  tlsEnabled: true  
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRuleEngine On
    # Allow traffic coming from: Primary DP Egress, Secondary DP Egress, Studio (Sheffield), DSD VPN, Quantum (x3 ranges), Lucas Cairns (Home), ARK (x5 ranges)
    nginx.ingress.kubernetes.io/whitelist-source-range: 18.130.83.42/32,52.56.168.163/32,217.33.148.210/29,81.134.202.29/32,212.137.36.230/32,62.25.109.197/32,195.92.38.16/28,188.210.212.86/32,195.59.75.0/24,194.33.192.0/25,194.33.193.0/25,194.33.196.0/25,194.33.197.0/25
    nginx.ingress.kubernetes.io/server-snippet: |
       add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

