---

- name: baseline
  hosts: all
  roles:
    - base
    - jnv.unattended-upgrades
    - role: singleplatform-eng.users
      tags:
      - users
    - provisioning

- hosts: bounce
  roles:
    - geerlingguy.nginx

- hosts: ci
  roles:
    - docker
    - jenkins

- hosts: hub
  roles:
    - hub-containers
    - geerlingguy.nginx
    - letsencrypt
