---

- name: baseline
  hosts: all
  roles:
    - base
    - jnv.unattended-upgrades
    - role: singleplatform-eng.users
      tags:
      - users
    - provisioning

- hosts: bounce
  roles:
    - geerlingguy.nginx
    - geerlingguy.firewall
    - logrotate

- hosts: hub
  roles:
    - hub-containers
    - geerlingguy.nginx
    - geerlingguy.firewall
    - letsencrypt
