version: "3"

services:
  hub-be:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      HUB_EXT_FILE_URL: https://drupal.digital-hub-stage.hmpps.dsd.io/sites/default/files
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
      - /content/moj_dhub_prod001_app/usr/share/nginx/html/moj_be/sites/default/files:/var/www/html/sites/default/files

  hub-db:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /data/hub-db:/var/lib/mysql:rw

  hub-matomo:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /data/moj_dhub_matomo_config:/var/www/html/config:rw

  hub-node:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      APP_NAME: HMP Staging
      NODE_ENV: production
      DRUPAL_APP_URI: http://drupal.digital-hub-stage.hmpps.dsd.io
      MATOMO_URL: "foo.bar"
      MATOMO_TOKEN: "foobar"
      MATOMO_API_URI: http://hub-matomo
      ENABLE_PRISON_SWITCH: "true"

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites: